//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANG_CAO
    {
        public int STT { get; set; }
        public string TenCTy { get; set; }
        public string Hinh_Minh_Hoa { get; set; }
        public string HREF { get; set; }
        public Nullable<System.DateTime> Ngay_bat_dau { get; set; }
        public Nullable<System.DateTime> Ngay_het_han { get; set; }
    }
}
