//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAC_GIA
    {
        public int Mtg { get; set; }
        public string Ten_tac_gia { get; set; }
        public string Dia_chi { get; set; }
        public string Dien_thoai { get; set; }
    }
}
