//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_DAT_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_DAT_HANG()
        {
            this.CT_DAT_HANG = new HashSet<CT_DAT_HANG>();
        }
    
        public int Sdh { get; set; }
        public Nullable<int> Mkh { get; set; }
        public System.DateTime Ngay_dat_hang { get; set; }
        public Nullable<decimal> Tri_gia { get; set; }
        public bool Da_giao_hang { get; set; }
        public Nullable<System.DateTime> Ngay_giao_hang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DAT_HANG> CT_DAT_HANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
