//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public int Ms { get; set; }
        public string Ten_sach { get; set; }
        public Nullable<decimal> Don_gia { get; set; }
        public string Don_vi_tinh { get; set; }
        public string Mo_ta { get; set; }
        public string Hinh_minh_hoa { get; set; }
        public Nullable<int> Mcd { get; set; }
        public Nullable<int> Mnxb { get; set; }
        public Nullable<System.DateTime> Ngay_cap_nhat { get; set; }
        public Nullable<int> So_luong_ban { get; set; }
        public Nullable<int> So_lan_xem { get; set; }
        public Nullable<int> so_luong_con { get; set; }
    
        public virtual CHU_DE CHU_DE { get; set; }
        public virtual NHA_XUAT_BAN NHA_XUAT_BAN { get; set; }
    }
}
